services:
  server:
    image: faq-server:latest
    volumes:
      - ./configs/config.toml:/app/configs/config.toml
      - ./migrations:/app/migrations
    environment:
      CONFIG_PATH: ${CONFIG_PATH}
      SERVER_HOST: ${SERVER_HOST}
      SERVER_PORT: ${SERVER_PORT}
      DEFAULT_API: ${DEFAULT_API}
      READ_TIMEOUT: ${READ_TIMEOUT}
      WRITE_TIMEOUT: ${WRITE_TIMEOUT}
      IDLE_TIMEOUT: ${IDLE_TIMEOUT}
      POSTGRES_HOST: ${POSTGRES_HOST}
      POSTGRES_PORT: ${POSTGRES_PORT}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB_NAME: ${POSTGRES_DB_NAME}
      POSTGRES_SSL_MODE: ${POSTGRES_SSL_MODE}
      POSTGRES_MIGRATIONS_PATH: ${POSTGRES_MIGRATIONS_PATH}
      JWT_SECREY_KEY: ${JWT_SECREY_KEY}
      ACCESS_TOKEN_EXP: ${ACCESS_TOKEN_EXP}
    ports:
      - "4400:4400"
    restart: unless-stopped
    depends_on:
      - postgres
    network_mode: host

  postgres:
    image: postgres:17
    volumes:
      - /private/var/lib/postgresql:/var/lib/postgresql
    environment:
      POSTGRES_DB: ${POSTGRES_DB_NAME}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U usr -d db"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped
